/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "hello_constants.h"

namespace hello {

const helloConstants g_hello_constants;

helloConstants::helloConstants() {
}

} // namespace

