// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "UserExchange.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace hello;

class UserExchangeHandler : virtual public UserExchangeIf {
 public:
  UserExchangeHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  int32_t add_user(const User& u) {
    // Your implementation goes here
    printf("add_user\n");
  }

  void get_user(User& _return, const int32_t uid) {
    // Your implementation goes here
    printf("get_user\n");
  }

  void clear_list() {
    // Your implementation goes here
    printf("clear_list\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<UserExchangeHandler> handler(new UserExchangeHandler());
  shared_ptr<TProcessor> processor(new UserExchangeProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

