/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef logger_CONSTANTS_H
#define logger_CONSTANTS_H

#include "logger_types.h"

namespace logger {

class loggerConstants {
 public:
  loggerConstants();

};

extern const loggerConstants g_logger_constants;

} // namespace

#endif
