// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Logger.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace logger;

class LoggerHandler : virtual public LoggerIf {
 public:
  LoggerHandler() {
    // Your initialization goes here
  }

  void log(const LogMessage& lm) {
    // Your implementation goes here
    printf("log\n");
  }

  void batch(const LogMessageBatch& lmb) {
    // Your implementation goes here
    printf("batch\n");
  }

  void getLastMessage(LogMessage& _return) {
    // Your implementation goes here
    printf("getLastMessage\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<LoggerHandler> handler(new LoggerHandler());
  shared_ptr<TProcessor> processor(new LoggerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

