
#ifndef APP_UTILITY_CONFIG_H_
#define APP_UTILITY_CONFIG_H_

#include "net/include/config.h"


//Define to 1 if you want to use the encrypting key generated by net CA server
#define H_PROVIDE_NET_CA_ENCRYPT 1

#if H_PROVIDE_NET_CA_ENCRYPT

#if !H_PROVIDE_CURL 
#error "This class depend on net::CURLService, net::CURLWork and so on, please recompile osl with H_PROVIDE_CURL flag on, H_PROVIDE_CURL is defined in libcommon/src/net/include/config.h"
#endif // end of #if !H_PROVIDE_CURL 

#if !H_PROVIDE_IDEA_ENCRYPT 
#error "H_PROVIDE_NET_CA_ENCRYPT depend on H_PROVIDE_IDEA_ENCRYPT"
#endif // end of #if !H_PROVIDE_IDEA_ENCRYPT


#endif // end of #if H_PROVIDE_NET_CA_ENCRYPT





#endif // end of #ifndef QAPP_UTILITY_CONFIG_H_




