/**
 *	slrsa.h - header file for slrsa.c
 *	Revision 1.00 - weizili 2011/2/29
 */

#ifndef _SL_RSA_H_
#define _SL_RSA_H_

#ifdef __cplusplus
extern "C" {
#endif

    /**
     *  slrsa_sign() signs the message digest m of size m_len using the private
     *  key generated by 360KeyMgr. It stores the signature in sigret
     *  and the signature size in siglen. sigret must point to at least 128
     *  bytes of memory.
     *
     *  slrsa_verify() verifies that the signature sigbuf of size siglen matches
     *  a given message digest m of size m_len. publickey is the signer's
     *  public key.
     *
     *  slrsa_sign() returns 1 on success, 0 otherwise.
     *  slrsa_verify() returns 1 on successful verification, 0 otherwise.
     */
    int slrsa_sign( const unsigned char*        m, 
                    const unsigned int          m_len,
                    const unsigned char*        private_key, //unsigned char[706]
                    unsigned char*              sigret, 
                    unsigned int*               siglen );

    int slrsa_verify( const unsigned char*      m, 
                      const unsigned int        m_len,
                      const unsigned char*      public_key,//unsigned char[258]
                      const unsigned char*      sigbuf, 
                      const unsigned int        siglen );


    /**
     * returns 1 on success, 0 otherwise.
     */
    int slrsa_public_encrypt( const unsigned char*      m, 
                              const unsigned int        m_len,
                              const unsigned char*      public_key,//unsigned char[258]
                              unsigned char*            sigret, 
                              unsigned int*             siglen );
    int slrsa_private_decrypt( const unsigned char*     sig, 
                               const unsigned int       sig_len,
                               const unsigned char*     private_key,//unsigned char[706]
                               unsigned char*           plain_data, 
                               unsigned int*            plain_data_len );
    int slrsa_private_encrypt( const unsigned char*     m, 
                               const unsigned int       m_len,
                               const unsigned char*     private_key,//unsigned char[706]
                               unsigned char*           sigret, 
                               unsigned int*            siglen );
    int slrsa_public_decrypt( const unsigned char*      sig, 
                              const unsigned int        sig_len,
                              const unsigned char*      public_key,//unsigned char[258]
                              unsigned char*            plain_data, 
                              unsigned int*             plain_data_len );

#ifdef __cplusplus
}
#endif



#endif

