//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by PLAYMP3.rc
//
#define IDD_PLAYMP3_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_BKG                         129
#define IDB_LIST                        130
#define IDB_PLAY                        131
#define IDB_UP_W                        132
#define IDB_DOWN_W                      133
#define IDB_ADD_W                       134
#define IDB_SUB_W                       135
#define IDB_UP_B                        136
#define IDB_DOWN_B                      137
#define IDB_ADD_B                       138
#define IDB_SUB_B                       139
#define IDB_LEFT_W                      140
#define IDB_LEFT_B                      141
#define IDB_RIGHT_W                     142
#define IDB_RIGHT_B                     143
#define IDB_PLAYMP3_W                   144
#define IDB_PLAYMP3_B                   145
#define IDB_SPAUSE_B                    146
#define IDB_SPAUSE_W                    147
#define IDB_CANCEL_W                    148
#define IDB_CANCEL_B                    149
#define IDB_RANDOM_W                    150
#define IDB_RANDOM_B                    151
#define IDB_ROUND_W                     152
#define IDB_ROUND_B                     153
#define IDB_BIGORSMALL_W                154
#define IDB_BIGORSMALL_B                155
#define IDB_CLOSE_W                     156
#define IDB_CLOSE_B                     157
#define IDB_STOP_W                      158
#define IDB_STOP_B                      159
#define IDB_TIAO1                       160
#define IDB_POINT1                      161
#define IDB_TIAO2                       162
#define IDB_POINT2                      163
#define IDB_volume                      164
#define IDD_OPENFILE                    165
#define IDB_BKG1                        166
#define IDB_CURRENTLIST_B               170
#define IDB_CURRENTLIST_W               171
#define IDB_MUTE                        172
#define IDB_round                       173
#define IDB_random                      174
#define IDB_norandomround               175
#define IDI_MP3                         188
#define IDI_WMA                         189
#define IDB_OPEN_ADD_W                  195
#define IDB_OPEN_ADD_B                  196
#define IDB_OPEN_CANCEL_W               197
#define IDB_OPEN_CANCEL_B               198
#define IDB_OPEN_ALL_W                  199
#define IDB_OPEN_ALL_B                  200
#define IDB_OPEN_BKG                    202
#define IDB_TIAO_STATE                  203
#define IDB_BRIGHT_TIAO2                226
#define IDB_Q1                          228
#define IDB_Q2                          229
#define IDB_Q3                          230
#define IDB_Q4                          231
#define IDB_Q5                          232
#define IDB_Q6                          233
#define IDB_Q7                          234
#define IDB_Q8                          235
#define IDB_Q9                          236
#define IDB_Q10                         237
#define IDB_tiao_blue                   245
#define IDB_OPEN_UP_W                   246
#define IDB_OPEN_DOWN_W                 247
#define IDB_OPEN_UP_B                   248
#define IDB_OPEN_DOWN_B                 249
#define IDB_testdian                    251
#define IDB_testtiao                    252
#define IDB_VOL_TIAO                    255
#define IDB_VOL_DIAN                    256
#define IDB_STATE_TIAO                  258
#define IDB_STATE_DIAN                  259
#define IDB_BLACK_VOL_DIAN              260
#define IDB_BLACK_STATE_DIAN            261
#define IDD_NEW_OPENFILE                262
#define IDI_PATH                        263
#define IDB_OPENFILE_UP1                264
#define IDB_OPENFILE_UP2                265
#define IDC_LIST1                       1000
#define IDC_LIST                        1000
#define IDC_PATH                        1000
#define IDC_BUTTON1                     1001
#define IDC_OK                          1002
#define IDC_ALL                         1002
#define IDC_BUTTON2                     1003
#define IDC_BUTTONDOWN                  1003
#define IDC_ADD                         1003
#define IDC_POS                         1004
#define IDC_EXIT                        1004
#define IDC_VOLUME                      1005
#define IDC_MUTE                        1006
#define IDC_SLIDER_GRAPH                1007
#define IDC_EDIT1                       1008
#define IDC_x                           1008
#define IDC_EDIT2                       1008
#define IDC_BUTTON3                     1010
#define IDC_LISTCTRL                    1012
#define IDC_UP                          1013
#define IDC_STATIC1                     1015
#define IDC_LRC                         1016
#define IDC_tiao_blue                   1017
#define IDC_STATIC123                   1020
#define IDC_STATIC2                     1021
#define IDC_LIST2                       1022
#define IDC_FILE                        1022
#define IDC_PLAYTIME                    1025
#define IDC_LRCNEW                      1026
#define IDC_PLAYING                     1027
#define IDC_NAMEING                     1028
#define IDC_dian                        1029
#define IDC_tiao                        1030
#define IDC_VOL_TIAO                    1033
#define IDC_VOL_DIAN                    1034
#define IDC_STATE_DIAN                  1035
#define IDC_STATE_TIAO                  1036
#define IDC_ALLTIME                     1038
#define IDC_CTRL                        1039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        266
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
