/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "logger_constants.h"

namespace logger {

const loggerConstants g_logger_constants;

loggerConstants::loggerConstants() {
}

} // namespace

